### ISSUE TITLE
MainTestDockerSuite keeps failing randomly

### ISSUE THREAD

**Issue by rcannood** [data-intuitive/viash#47]
When `sbt test` due to MainTestDockerSuite, the output often looks like this:

```
[info] - Check standard test output with leading and trailing arguments *** FAILED ***
[info]   java.lang.RuntimeException: Only 1 out of 2 test scripts succeeded!
[info]   at com.dataintuitive.viash.ViashTest$.apply(ViashTest.scala:80)
[info]   at com.dataintuitive.viash.Main$.main(Main.scala:60)
[info]   at com.dataintuitive.viash.TestHelper$.$anonfun$testMain$1(TestHelper.scala:31)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[info]   at scala.Console$.withOut(Console.scala:167)
[info]   at com.dataintuitive.viash.TestHelper$.testMain(TestHelper.scala:31)
[info]   at com.dataintuitive.viash.MainTestDockerSuite.$anonfun$new$3(MainTestDockerSuite.scala:67)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

**Comment by rcannood** [comment]
@Grifs If you could try to take a look at this, that'd be simply fantastic! :)

Otherwise, I'll take a look at it when I have the time.

**Comment by Grifs** [comment]
Failure is due parallelized tests.
Intellij IDEA doesn't parallelize -> test always succeed
`sbt test` -> randomly fails
`sbt 'testOnly MainTestDockerSuite'` -> always works
`sbt 'set Test / parallelExecution := false' test` -> always works
setting the parallelExecution to false in build.sbt -> always works

**Comment by rcannood** [comment]
This was solved in 0.6.0 or so. What solved this issue again?
